services:
  web: # Seu Next.js
    container_name: nextjs-app
    build:
      context: ./arezdelivery-front # Caminho para a pasta do Next.js
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - api # O front só sobe depois do back estar pronto
    restart: unless-stopped
    networks:
      - cloudflare-network

  api: # Seu NestJS
    container_name: nestjs-api
    build:
      context: ../arezdelivery-api # Caminho para a pasta do NestJS
      dockerfile: Dockerfile
    expose:
      - "3001" # Porta do NestJS
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - cloudflare-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: unless-stopped
    # Mantendo o Quick Tunnel apontado para o front-end
    command: tunnel --url http://web:3000
    networks:
      - cloudflare-network

networks:
  cloudflare-network:
    name: cloudflare-network