version: '3.8'

services:
  web:
    container_name: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    # Usamos expose para que a Cloudflare acesse internamente, sem abrir para a rede local
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - cloudflare-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: unless-stopped
    # Alteramos o comando para gerar uma URL aleatória temporária
    command: tunnel --url http://web:3000
    networks:
      - cloudflare-network

networks:
  cloudflare-network:
    name: cloudflare-network