services:
  web:
    container_name: nextjs-app
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - cloudflare-network

  api:
    container_name: nestjs-api
    build:
      context: ../arezdelivery-api
      dockerfile: Dockerfile
    expose:
      - "3001"
    environment:
      - NODE_ENV=production
      - POSTGRES_URL=${POSTGRES_URL} # Passa a URL de conexão para o NestJS
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    depends_on:
      - db # O NestJS aguarda o banco iniciar
    restart: unless-stopped
    networks:
      - cloudflare-network

  db:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - "127.0.0.1:5432:5432" # Expõe apenas para o seu servidor local (segurança)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cloudflare-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: unless-stopped
    command: tunnel --url http://web:3000
    networks:
      - cloudflare-network

networks:
  cloudflare-network:
    name: cloudflare-network

# Declaração do volume persistente para não perder os dados do banco
volumes:
  postgres_data: